version: 2.1

parameters:
  manual_test:
    type: boolean
    default: false

executors:
  docker-img:
    docker:
      - image: cimg/python:3.9.5

jobs:
  build:
    executor:
      docker-img
    steps:
      - checkout
      - run: echo "Hello world"

workflows:
  commit:
    jobs:
      - build
  manual_test:
    jobs:
      - build
    when: << pipeline.parameters.manual_test >>
